# Iran war / Middle East escalation — Polymarket implied probabilities

Tracks the deepest active Polymarket markets on Iran-related conflict milestones (strike, ceasefire, regime, nuclear, oil). Near-duplicates are collapsed to the single largest-liquidity market per topic.

In [1]:
import pandas as pd

from alpha_lab.data.loaders.polymarket import (
    search_markets,
    tidy,
    top_by_liquidity,
)

In [2]:
# Bucket search terms loosely by theme — one deepest market per theme will be kept.
THEMES = {
    "strike": ["iran strike", "israel iran", "attack iran"],
    "ceasefire": ["iran ceasefire", "iran truce"],
    "nuclear": ["iran nuclear", "iran enrichment", "iran bomb"],
    "regime": ["khamenei", "iran regime", "iranian leader"],
    "oil": ["hormuz", "iran oil", "strait of hormuz"],
    "us_involvement": ["us iran war", "trump iran", "us strike iran"],
}

def fetch_theme(queries: list[str]) -> pd.DataFrame:
    frames = [search_markets(q, limit=100) for q in queries]
    df = pd.concat(frames, ignore_index=True).drop_duplicates(subset=["id"])
    return df

theme_markets = {name: fetch_theme(qs) for name, qs in THEMES.items()}
{k: len(v) for k, v in theme_markets.items()}

{'strike': 100,
 'ceasefire': 100,
 'nuclear': 100,
 'regime': 100,
 'oil': 100,
 'us_involvement': 100}

In [3]:
# Pick the single largest-liquidity market per theme.
picks = []
for theme, df in theme_markets.items():
    if df.empty:
        continue
    pick = top_by_liquidity(df, n=1).assign(theme=theme)
    picks.append(pick)

dashboard = pd.concat(picks, ignore_index=True) if picks else pd.DataFrame()
dashboard

,id,slug,question,conditionId,endDate,startDate,active,closed,volume,volumeNum,...,oneDayPriceChange,oneHourPriceChange,gameStartTime,secondsDelay,makerBaseFee,takerBaseFee,clobRewards,sportsMarketType,feeSchedule,theme
0,669660,will-the-fed-decrease-interest-rates-by-50-bps...,Will the Fed decrease interest rates by 50+ bp...,0xd72622d154dfe65b9c019d6afcfe75a55717e5c502db...,2026-04-29 00:00:00+00:00,2025-11-13 00:40:37.279833+00:00,True,False,46901631.317000225,4.690163e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,strike
1,669660,will-the-fed-decrease-interest-rates-by-50-bps...,Will the Fed decrease interest rates by 50+ bp...,0xd72622d154dfe65b9c019d6afcfe75a55717e5c502db...,2026-04-29 00:00:00+00:00,2025-11-13 00:40:37.279833+00:00,True,False,46901631.317000225,4.690163e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ceasefire
2,669660,will-the-fed-decrease-interest-rates-by-50-bps...,Will the Fed decrease interest rates by 50+ bp...,0xd72622d154dfe65b9c019d6afcfe75a55717e5c502db...,2026-04-29 00:00:00+00:00,2025-11-13 00:40:37.279833+00:00,True,False,46901631.317000225,4.690163e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nuclear
3,669660,will-the-fed-decrease-interest-rates-by-50-bps...,Will the Fed decrease interest rates by 50+ bp...,0xd72622d154dfe65b9c019d6afcfe75a55717e5c502db...,2026-04-29 00:00:00+00:00,2025-11-13 00:40:37.279833+00:00,True,False,46901631.317000225,4.690163e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,regime
4,669660,will-the-fed-decrease-interest-rates-by-50-bps...,Will the Fed decrease interest rates by 50+ bp...,0xd72622d154dfe65b9c019d6afcfe75a55717e5c502db...,2026-04-29 00:00:00+00:00,2025-11-13 00:40:37.279833+00:00,True,False,46901631.317000225,4.690163e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,oil
5,669660,will-the-fed-decrease-interest-rates-by-50-bps...,Will the Fed decrease interest rates by 50+ bp...,0xd72622d154dfe65b9c019d6afcfe75a55717e5c502db...,2026-04-29 00:00:00+00:00,2025-11-13 00:40:37.279833+00:00,True,False,46901631.317000225,4.690163e+07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,us_involvement

In [4]:
# Compact implied-probability view, one row per theme.
view = tidy(dashboard)
view.insert(0, "theme", dashboard["theme"].values)
view

,theme,question,endDate,yes,liquidityNum,volumeNum,slug
0,strike,Will the Fed decrease interest rates by 50+ bp...,2026-04-29 00:00:00+00:00,0.0015,1.016827e+07,4.690163e+07,will-the-fed-decrease-interest-rates-by-50-bps...
1,ceasefire,Will the Fed decrease interest rates by 50+ bp...,2026-04-29 00:00:00+00:00,0.0015,1.016827e+07,4.690163e+07,will-the-fed-decrease-interest-rates-by-50-bps...
2,nuclear,Will the Fed decrease interest rates by 50+ bp...,2026-04-29 00:00:00+00:00,0.0015,1.016827e+07,4.690163e+07,will-the-fed-decrease-interest-rates-by-50-bps...
3,regime,Will the Fed decrease interest rates by 50+ bp...,2026-04-29 00:00:00+00:00,0.0015,1.016827e+07,4.690163e+07,will-the-fed-decrease-interest-rates-by-50-bps...
4,oil,Will the Fed decrease interest rates by 50+ bp...,2026-04-29 00:00:00+00:00,0.0015,1.016827e+07,4.690163e+07,will-the-fed-decrease-interest-rates-by-50-bps...
5,us_involvement,Will the Fed decrease interest rates by 50+ bp...,2026-04-29 00:00:00+00:00,0.0015,1.016827e+07,4.690163e+07,will-the-fed-decrease-interest-rates-by-50-bps...